[manifest]
version = "1.1"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local t = create_UIBox_generic_options({back_func = 'options',contents = {create_tabs("
position = "before"
match_indent = true
overwrite = false
payload = "tabs[#tabs+1] = DV.create_settings_tab(#tabs)"
